---
title: "p8105_hw2_yh3964"
author: "Yirou Hu"
date: "2025-09-26"
output: github_document
---
# Problem 0
We import the datasets and create all the required files with name. 
```{r}
library(tidyverse)
library(readxl)
```

# Problem 1
We will do data cleaning for pols-month.csv firstly. 

- break up the variable mon into integer variables year, month, and day; 
- replace month number with month name; 
- create a president variable taking values gop and dem, 
- remove prez_dem and prez_gop
- remove the day variable.

```{r}
pols_month = read_csv("fivethirtyeight_datasets/pols-month.csv") |>
  janitor::clean_names() |>
  separate(mon, into = c("year", "month", "day"), sep = "-") |>
  mutate(
    month = case_match(
      month, 
    "01"~"Jan",
    "02"~"Feb",
    "03"~"Mar",
    "04"~"Apr",
    "05"~"May",
    "06"~"Jun",
    "07"~"Jul",
    "08"~"Aug",
    "09"~"Sep",
    "10"~"Oct",
    "11"~"Nov",
    "12"~"Dec")
  )|>
  mutate(
    president=case_match(
      prez_gop,
    0~"dem",
    1~"gop",
    2~"gop"
    )
  )|>
  mutate(year = as.integer(year), day = as.integer(day)) |>
  select(-c("day", "prez_gop", "prez_dem"))
```
